name: Enterprise User Report

on:
  # Scheduled to run every night at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  generate-user-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Collect enterprise user data
      id: collect-users
      run: node scripts/collect-users.js
      env:
        GITHUB_TOKEN: ${{ secrets.ENTERPRISE_PAT }}
        GITHUB_ENTERPRISE: ${{ vars.ENTERPRISE_SLUG }}
        GITHUB_REPOSITORY: ${{ github.repository }}
    
    - name: Format issue content
      id: format-issue
      run: node scripts/format-issue.js
      env:
        USER_DATA_FILE: users-data.json
    
    - name: Create GitHub issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ENTERPRISE_PAT }}
        script: |
          const fs = require('fs');
          const issueContent = fs.readFileSync('issue-content.md', 'utf8');
          const today = new Date().toISOString().split('T')[0];
          
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Enterprise User Report - ${today}`,
            body: issueContent,
            labels: ['enterprise-report', 'automated']
          });
          
          console.log(`Created issue #${issue.data.number}`);